$ErrorActionPreference = 'Stop'

$repo = 'lordkeremello45/HWcontrol2.0'
$api = "https://api.github.com/repos/$repo/releases"
$headers = @{ 'Accept' = 'application/vnd.github+json'; 'User-Agent' = 'HWControl-Installer' }

Write-Host 'HWControl Windows Installer' -ForegroundColor Cyan
Write-Host 'Resolving the latest Windows release...'

$releases = Invoke-RestMethod -Uri $api -Headers $headers
$release = $releases | Where-Object { $_.tag_name -match '-windows$' -and -not $_.draft } | Select-Object -First 1
if (-not $release) { throw 'No Windows release is currently available.' }

$msi = $release.assets | Where-Object { $_.name -match '\.msi$' } | Select-Object -First 1
$sha = $release.assets | Where-Object { $_.name -match '\.sha256$' } | Select-Object -First 1
if (-not $msi) {
  throw "The latest Windows release ($($release.tag_name)) does not publish an MSI yet. Publish a release generated by .github/workflows/release.yml."
}
if (-not $sha) {
  throw "The latest Windows release ($($release.tag_name)) has no SHA-256 manifest. Installation is blocked."
}

$temp = Join-Path $env:TEMP "HWControl-$($release.tag_name).msi"
$shaTemp = Join-Path $env:TEMP "HWControl-$($release.tag_name).sha256"
Write-Host "Downloading $($msi.name)..."
Invoke-WebRequest -Uri $msi.browser_download_url -Headers $headers -OutFile $temp
Invoke-WebRequest -Uri $sha.browser_download_url -Headers $headers -OutFile $shaTemp

$expected = Get-Content $shaTemp | ForEach-Object {
  if ($_ -match '^([0-9a-fA-F]{64})\s+(.+\.msi)$') { [PSCustomObject]@{ Hash = $matches[1].ToLower(); File = $matches[2] } }
} | Where-Object { $_.File -eq $msi.name } | Select-Object -First 1
if (-not $expected) { throw "No SHA-256 entry for $($msi.name) was found. Installation is blocked." }

$actual = (Get-FileHash $temp -Algorithm SHA256).Hash.ToLower()
if ($actual -ne $expected.Hash) { throw 'SHA-256 verification failed. The installer was not launched.' }
Write-Host 'SHA-256 verification: OK' -ForegroundColor Green

Write-Host "Starting HWControl $($release.tag_name) installer..."
Start-Process msiexec.exe -ArgumentList '/i', "`"$temp`"" -Wait
Write-Host 'HWControl installation finished.' -ForegroundColor Green
