#!/bin/sh
set -eu

REPO='lordkeremello45/HWcontrol2.0'
API="https://api.github.com/repos/$REPO/releases"
TMP_DIR="${TMPDIR:-/tmp}/hwcontrol-installer"
mkdir -p "$TMP_DIR"

printf '\nHWControl macOS Installer\n'
printf '%s\n' 'Resolving the latest Apple Silicon release...'

release_json="$(curl -fsSL -H 'Accept: application/vnd.github+json' -H 'User-Agent: HWControl-Installer' "$API")"
tag="$(printf '%s' "$release_json" | python3 -c 'import json,sys; r=json.load(sys.stdin); print(next(x["tag_name"] for x in r if x["tag_name"].endswith("-macos") and not x["draft"]))')"
pkg_url="$(printf '%s' "$release_json" | python3 -c 'import json,sys; r=json.load(sys.stdin); x=next(x for x in r if x["tag_name"].endswith("-macos") and not x["draft"]); print(next((a["browser_download_url"] for a in x["assets"] if a["name"].endswith(".pkg")), ""))')"
sha_url="$(printf '%s' "$release_json" | python3 -c 'import json,sys; r=json.load(sys.stdin); x=next(x for x in r if x["tag_name"].endswith("-macos") and not x["draft"]); print(next((a["browser_download_url"] for a in x["assets"] if a["name"].endswith(".sha256")), ""))')"

if [ -z "$pkg_url" ]; then
  echo "The latest macOS release ($tag) does not publish a PKG yet. Publish a release generated by .github/workflows/release.yml." >&2
  exit 1
fi

pkg="$TMP_DIR/HWControl-$tag.pkg"
curl -fL -o "$pkg" "$pkg_url"

if [ -n "$sha_url" ]; then
  expected="$(curl -fsSL "$sha_url" | awk '/\.pkg$/ {print $1; exit}')"
  if [ -n "$expected" ]; then
    actual="$(shasum -a 256 "$pkg" | awk '{print $1}')"
    [ "$actual" = "$expected" ] || { echo 'SHA-256 verification failed. The installer was not launched.' >&2; exit 1; }
    echo 'SHA-256 verification: OK'
  fi
fi

echo "Starting HWControl $tag installer..."
sudo installer -pkg "$pkg" -target /
echo 'HWControl installation finished.'
